// Bidirectional country name <-> ISO 3166-1 alpha-2 code mapping.
// Covers all federations in scripts/scrape.ts plus Chess-Results.com variants.

const NAME_TO_CODE: Record<string, string> = {
  // Europe
  'germany': 'DE',
  'france': 'FR',
  'spain': 'ES',
  'england': 'GB',
  'scotland': 'GB',
  'wales': 'GB',
  'united kingdom': 'GB',
  'great britain': 'GB',
  'italy': 'IT',
  'poland': 'PL',
  'netherlands': 'NL',
  'holland': 'NL',
  'russia': 'RU',
  'ukraine': 'UA',
  'austria': 'AT',
  'switzerland': 'CH',
  'czech republic': 'CZ',
  'czechia': 'CZ',
  'hungary': 'HU',
  'sweden': 'SE',
  'norway': 'NO',
  'denmark': 'DK',
  'finland': 'FI',
  'belgium': 'BE',
  'portugal': 'PT',
  'greece': 'GR',
  'turkey': 'TR',
  'serbia': 'RS',
  'croatia': 'HR',
  'slovenia': 'SI',
  'slovakia': 'SK',
  'romania': 'RO',
  'bulgaria': 'BG',
  'georgia': 'GE',
  'armenia': 'AM',
  'azerbaijan': 'AZ',
  'lithuania': 'LT',
  'latvia': 'LV',
  'estonia': 'EE',
  'belarus': 'BY',
  'moldova': 'MD',
  'north macedonia': 'MK',
  'macedonia': 'MK',
  'bosnia and herzegovina': 'BA',
  'bosnia': 'BA',
  'montenegro': 'ME',
  'albania': 'AL',
  'iceland': 'IS',
  'ireland': 'IE',
  'luxembourg': 'LU',
  'cyprus': 'CY',
  'malta': 'MT',
  'andorra': 'AD',
  'liechtenstein': 'LI',
  'san marino': 'SM',
  'monaco': 'MC',
  'kosovo': 'XK',
  'faroe islands': 'FO',

  // Americas
  'united states': 'US',
  'united states of america': 'US',
  'usa': 'US',
  'us': 'US',
  'canada': 'CA',
  'mexico': 'MX',
  'argentina': 'AR',
  'brazil': 'BR',
  'colombia': 'CO',
  'peru': 'PE',
  'chile': 'CL',
  'venezuela': 'VE',
  'ecuador': 'EC',
  'uruguay': 'UY',
  'paraguay': 'PY',
  'bolivia': 'BO',
  'cuba': 'CU',
  'puerto rico': 'PR',
  'costa rica': 'CR',
  'panama': 'PA',
  'dominican republic': 'DO',
  'guatemala': 'GT',
  'el salvador': 'SV',
  'honduras': 'HN',
  'nicaragua': 'NI',
  'jamaica': 'JM',
  'trinidad and tobago': 'TT',
  'barbados': 'BB',
  'guyana': 'GY',
  'suriname': 'SR',
  'haiti': 'HT',

  // Asia
  'india': 'IN',
  'china': 'CN',
  'japan': 'JP',
  'south korea': 'KR',
  'korea': 'KR',
  'philippines': 'PH',
  'indonesia': 'ID',
  'vietnam': 'VN',
  'viet nam': 'VN',
  'malaysia': 'MY',
  'singapore': 'SG',
  'thailand': 'TH',
  'myanmar': 'MM',
  'burma': 'MM',
  'bangladesh': 'BD',
  'sri lanka': 'LK',
  'pakistan': 'PK',
  'iran': 'IR',
  'iraq': 'IQ',
  'united arab emirates': 'AE',
  'uae': 'AE',
  'saudi arabia': 'SA',
  'qatar': 'QA',
  'kuwait': 'KW',
  'bahrain': 'BH',
  'jordan': 'JO',
  'lebanon': 'LB',
  'syria': 'SY',
  'uzbekistan': 'UZ',
  'kazakhstan': 'KZ',
  'mongolia': 'MN',
  'kyrgyzstan': 'KG',
  'tajikistan': 'TJ',
  'turkmenistan': 'TM',
  'afghanistan': 'AF',
  'nepal': 'NP',
  'cambodia': 'KH',
  'laos': 'LA',
  'taiwan': 'TW',
  'hong kong': 'HK',
  'macau': 'MO',
  'israel': 'IL',
  'palestine': 'PS',
  'oman': 'OM',
  'yemen': 'YE',
  'brunei': 'BN',

  // Africa
  'south africa': 'ZA',
  'egypt': 'EG',
  'morocco': 'MA',
  'tunisia': 'TN',
  'algeria': 'DZ',
  'nigeria': 'NG',
  'kenya': 'KE',
  'uganda': 'UG',
  'zimbabwe': 'ZW',
  'zambia': 'ZM',
  'botswana': 'BW',
  'namibia': 'NA',
  'ghana': 'GH',
  "cote d'ivoire": 'CI',
  'ivory coast': 'CI',
  'senegal': 'SN',
  'cameroon': 'CM',
  'angola': 'AO',
  'ethiopia': 'ET',
  'tanzania': 'TZ',
  'mozambique': 'MZ',
  'mali': 'ML',
  'burkina faso': 'BF',
  'mauritius': 'MU',
  'rwanda': 'RW',
  'libya': 'LY',
  'sudan': 'SD',
  'madagascar': 'MG',
  'malawi': 'MW',
  'seychelles': 'SC',
  'cape verde': 'CV',
  'maldives': 'MV',
  'togo': 'TG',
  'benin': 'BJ',

  // Oceania
  'australia': 'AU',
  'new zealand': 'NZ',
  'fiji': 'FJ',
  'papua new guinea': 'PG',
};

const CODE_TO_NAME: Record<string, string> = {
  AD: 'Andorra', AE: 'United Arab Emirates', AF: 'Afghanistan', AL: 'Albania',
  AM: 'Armenia', AO: 'Angola', AR: 'Argentina', AT: 'Austria',
  AU: 'Australia', AZ: 'Azerbaijan', BA: 'Bosnia and Herzegovina', BB: 'Barbados',
  BD: 'Bangladesh', BE: 'Belgium', BF: 'Burkina Faso', BG: 'Bulgaria',
  BH: 'Bahrain', BJ: 'Benin', BN: 'Brunei', BO: 'Bolivia', BR: 'Brazil', BW: 'Botswana',
  BY: 'Belarus', CA: 'Canada', CI: "Côte d'Ivoire", CL: 'Chile',
  CM: 'Cameroon', CN: 'China', CO: 'Colombia', CR: 'Costa Rica',
  CU: 'Cuba', CV: "Cape Verde", CY: 'Cyprus', CZ: 'Czech Republic', DE: 'Germany',
  DK: 'Denmark', DO: 'Dominican Republic', DZ: 'Algeria', EC: 'Ecuador',
  EE: 'Estonia', EG: 'Egypt', ES: 'Spain', ET: 'Ethiopia',
  FI: 'Finland', FJ: 'Fiji', FO: 'Faroe Islands', FR: 'France', GB: 'United Kingdom',
  GE: 'Georgia', GH: 'Ghana', GR: 'Greece', GT: 'Guatemala', GY: 'Guyana',
  HK: 'Hong Kong', HN: 'Honduras', HR: 'Croatia', HT: 'Haiti', HU: 'Hungary',
  ID: 'Indonesia', IE: 'Ireland', IL: 'Israel', IN: 'India',
  IQ: 'Iraq', IR: 'Iran', IS: 'Iceland', IT: 'Italy',
  JM: 'Jamaica', JO: 'Jordan', JP: 'Japan', KE: 'Kenya',
  KG: 'Kyrgyzstan', KH: 'Cambodia', KR: 'South Korea', KW: 'Kuwait',
  KZ: 'Kazakhstan', LA: 'Laos', LB: 'Lebanon', LI: 'Liechtenstein',
  LK: 'Sri Lanka', LT: 'Lithuania', LU: 'Luxembourg', LV: 'Latvia',
  LY: 'Libya', MA: 'Morocco', MC: 'Monaco', MD: 'Moldova',
  ME: 'Montenegro', MG: 'Madagascar', MK: 'North Macedonia', ML: 'Mali',
  MM: 'Myanmar', MN: 'Mongolia', MO: 'Macau', MT: 'Malta',
  MU: 'Mauritius', MV: 'Maldives', MW: 'Malawi', MX: 'Mexico', MY: 'Malaysia',
  MZ: 'Mozambique', NA: 'Namibia', NG: 'Nigeria', NI: 'Nicaragua',
  NL: 'Netherlands', NO: 'Norway', NP: 'Nepal', NZ: 'New Zealand',
  OM: 'Oman', PA: 'Panama', PE: 'Peru', PG: 'Papua New Guinea',
  PH: 'Philippines', PK: 'Pakistan', PL: 'Poland', PR: 'Puerto Rico',
  PS: 'Palestine', PT: 'Portugal', PY: 'Paraguay', QA: 'Qatar',
  RO: 'Romania', RS: 'Serbia', RU: 'Russia', RW: 'Rwanda',
  SA: 'Saudi Arabia', SC: 'Seychelles', SD: 'Sudan', SE: 'Sweden', SG: 'Singapore',
  SI: 'Slovenia', SK: 'Slovakia', SM: 'San Marino', SN: 'Senegal', SR: 'Suriname',
  SV: 'El Salvador', SY: 'Syria', TH: 'Thailand', TJ: 'Tajikistan',
  TM: 'Turkmenistan', TN: 'Tunisia', TO: 'Togo', TR: 'Turkey', TT: 'Trinidad and Tobago',
  TW: 'Taiwan', TZ: 'Tanzania', UA: 'Ukraine', UG: 'Uganda',
  US: 'United States', UY: 'Uruguay', UZ: 'Uzbekistan', VE: 'Venezuela',
  VN: 'Vietnam', XK: 'Kosovo', YE: 'Yemen', ZA: 'South Africa',
  ZM: 'Zambia', ZW: 'Zimbabwe',
  CH: 'Switzerland', AT_: 'Austria', // CH kept for Swiss
};

/**
 * Convert a country name to an ISO 3166-1 alpha-2 code.
 * Case-insensitive. Returns null if not found.
 */
export function countryNameToCode(name: string): string | null {
  if (!name) return null;
  return NAME_TO_CODE[name.trim().toLowerCase()] ?? null;
}

/**
 * Convert an ISO 3166-1 alpha-2 code to a country name.
 * Returns null if not found.
 */
export function countryCodeToName(code: string): string | null {
  if (!code) return null;
  return CODE_TO_NAME[code.trim().toUpperCase()] ?? null;
}
